new_local_repository(
    name = "vulkan_windows",
    build_file = "@//:build_files/vulkan_windows.BUILD",
    path = "C:\\VulkanSDK\\1.3.268.0",
)

new_local_repository(
    name = "vulkan_mac",
    build_file = "@//:build_files/vulkan_mac.BUILD",
    path = "/Applications/VulkanSDK/1.3.268.1/macOS",
)

new_local_repository(
    name = "vulkan_linux",
    build_file = "@//:build_files/vulkan_linux.BUILD",
    path = "/usr/vulkan/1.3.280.1/x86_64",
)
